[project]
name = "Subscribly"
version = "0.0.1"
description = "This project is for Predicting the churn for Subscribly App."
readme = "README.md"
authors = [
  {name = "Avanindra Bose", email = "avanindrabose0218@gmail.com"}
]
maintainers = [
  {name = "Avanindra Bose", email = "avanindrabose0218@gmail.com"}
]
classifiers = [
    # TODO
]
license = {text = "MIT"}
dependencies = [
  "typer",
  # Data
  "pandas>=2.0",
  "numpy>=1.24",

  # ML
  "scikit-learn>=1.3",

  # ML pipelines
  "mlflow>=2.9",
  "dvc>=3.0",

  # Config & utils
  "pyyaml",
  "joblib",
]
requires-python = ">= 3.10"

[project.optional-dependencies]
dev = [
    "matplotlib",
    "seaborn",
]
test = [
    "coverage",  # testing
    "pytest",  # testing
    "ruff",  # linting
    "ty", # checking types
    "ipdb", # debugging
]

[project.urls]
bugs = "https://github.com/AvanindraBose/Subscribly/issues"
changelog = "https://github.com/AvanindraBose/Subscribly/blob/master/changelog.md"
homepage = "https://github.com/AvanindraBose/Subscribly"

[project.scripts]
Subscribly = "Subscribly.cli:app"

[tool.ty]
# All rules are enabled as "error" by default; no need to specify unless overriding.
# Example override: relax a rule for the entire project (uncomment if needed).
# rules.TY015 = "warn"  # For invalid-argument-type, warn instead of error.

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # Pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "UP",  # pyupgrade
]

[tool.uv]
package = true
